<a href="https://colab.research.google.com/github/sudhanthiran/Python_Code_iNeuron/blob/Python-Assignments/Sudhanthiran_MLD6JUN_Python_Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Write a function so that the columns of the output matrix are powers of the input vector.

In [4]:
import numpy as np

def matrix_power(a,N=None,flag=False):
  return np.vander(a,N,flag)

value = [1,2,3,5]

print(matrix_power(value))

print(matrix_power(value,None,True))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [ ]:
def rollingWindowAverage(a,k):
  n = len(a)
  avg = []
  for i in range(0,n-k+1,1):
    #temp = (a[i] + a[i+1] + a[i+2])//3
    temp = sum_window(a[i:i+k])//k
    avg.append(temp)
  return avg
def sum_window(a):
  return sum(a)

value_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3

b = rollingWindowAverage(value_list,window)

for i in b:
  print(i)

5
4
5
6
9
28
49
72
84
93
116
